from os import system

CLEARSCREEN = lambda: system('cls')
WAITFORENTER = input

# Crucial
ADMINUSERNAME = "admin"

FILEHANDLER_USER = "users"
FILEHANDLER_SPEAKER_STATUS = "status"
FILEHANDLER_SPEAKER_STATUS_ACTIVE = "ACTIVE"
FILEHANDLER_SPEAKER_STATUS_PASSIVE = "PASSIVE"
FILEHANDLER_TOPIC = "topic"
FILEHANDLER_DESCRIPTION = "description"
FILEHANDLER_SPEAKER = "speakers"
FILEHANDLER_USERNAME = "username"
FILEHANDLER_PASSWORD = "password"
FILEHANDLER_NAME = "name"
FILEHANDLER_FILENAME = "users.txt"
FILEHANDLER_SPACE = " "

ADMIN_INSTRUCTION_LOGOUT = "logout"
ADMIN_INSTRUCTION_SPEAKERS = "speakers"
ADMIN_INSTRUCTION_SPEAKERS_ADD = "add"
ADMIN_INSTRUCTION_SPEAKERS_REMOVE = "remove"
ADMIN_INSTRUCTION_SPEAKERS_EDIT = "edit"
ADMIN_INSTRUCTION_SURVEY = "survey"
ADMIN_INSTRUCTION_SURVEY_CLOSE = "close"
ADMIN_INSTRUCTION_SURVEY_START = "start"


# Optional
INPUT_GLOBAL_LINE = "************************** "
INPUT_GLOBAL_QUITSTATEMENT = "quit"
INPUT_LOGIN_USERNAME = "enter username:"
INPUT_LOGIN_PASSWORD = "enter password:"
INPUT_ADMINPAGE_SPEAKER_NAME = 'fullname'
INPUT_ADMINPAGE_SPEAKER_TOPIC = 'presentation topic'
INPUT_ADMINPAGE_SPEAKER_DESCRIPTION = 'description'
INPUT_ADMINPAGE_SPEAKER_STATUS = "status"


ERROR_LOGIN_SPACEINPUT = "spaces not allowed in inputs"
ERROR_LOGIN_WRONGPASSWORD = "Wrong Password"
ERROR_LOGIN_EMPTYINPUT = "empty input not allowed"
ERROR_LOGIN_USERNAMENOTFOUND = "Unregistered username"
ERROR_ADMINPAGE_UNKNOWNCOMMAND = "Unknown command"
ERROR_ADMINPAGE_NOSPEAKER = "No speaker to show"


OUTPUT_SPEAKER_ADDITION_SUCCEED = "Speaker has been added successfully!"
OUTPUT_SPEAKER_DELETION_SUCCEED = "Speaker has been added successfully!"
OUTPUT_SPEAKER_EDITION_SUCCEED = "Editing Operation Done!"


