from os import system

CLEARSCREEN = lambda: system('cls')
WAITFORENTER = input

# Crucial
ADMINUSERNAME = "admin"

FILEHANDLER_USER = "users"
FILEHANDLER_SPEAKER = "speakers"
FILEHANDLER_SPEAKER_STATUS = "status"
FILEHANDLER_SPEAKER_STATUS_ACTIVE = "ACTIVE"
FILEHANDLER_SPEAKER_STATUS_PASSIVE = "PASSIVE"
FILEHANDLER_TOPIC = "topic"
FILEHANDLER_DESCRIPTION = "description"
FILEHANDLER_USERNAME = "username"
FILEHANDLER_PASSWORD = "password"
FILEHANDLER_NAME = "name"
FILEHANDLER_FILENAME = "users.txt"
FILEHANDLER_SPACE = " "
FILEHANDLER_SURVEY = 'survey'
FILEHANDLER_SURVEY_OWNER = 'owner'
FILEHANDLER_SURVEY_SINGLESURVEY = 'singlesurvey'
FILEHANDLER_SURVEY_SINGLESURVEY_participant = 'participant'
FILEHANDLER_SURVEY_SINGLESURVEY_COMMENT = 'comment'
FILEHANDLER_SURVEY_SINGLESURVEY_RATING = 'rating'


ADMIN_INSTRUCTION_LOGOUT = "logout"
ADMIN_INSTRUCTION_SPEAKERS = "speakers"
ADMIN_INSTRUCTION_SPEAKERS_ADD = "add"
ADMIN_INSTRUCTION_SPEAKERS_REMOVE = "remove"
ADMIN_INSTRUCTION_SPEAKERS_EDIT = "edit"
ADMIN_INSTRUCTION_SURVEY = "survey"
ADMIN_INSTRUCTION_SURVEY_CLOSE = "close"
ADMIN_INSTRUCTION_SURVEY_START = "start"
ADMIN_INSTRUCTION_VIEWALL = "viewall"

USER_INSTRUCTION_SURVEY = "survey"
USER_INSTRUCTION_LOGOUT = "logout"
USER_INSTRUCTION_SURVEY_START = 'start'


# Optional
INPUT_GLOBAL_LINE = "************************** "
INPUT_GLOBAL_QUITSTATEMENT = "quit"
INPUT_LOGIN_USERNAME = "enter username:"
INPUT_LOGIN_PASSWORD = "enter password:"
INPUT_ADMINPAGE_SPEAKER_NAME = 'fullname'
INPUT_ADMINPAGE_SPEAKER_TOPIC = 'presentation topic'
INPUT_ADMINPAGE_SPEAKER_DESCRIPTION = 'description'
INPUT_ADMINPAGE_SPEAKER_STATUS = "status"


ERROR_LOGIN_SPACEINPUT = "spaces not allowed in inputs"
ERROR_LOGIN_WRONGPASSWORD = "Wrong Password"
ERROR_LOGIN_EMPTYINPUT = "empty input not allowed"
ERROR_LOGIN_USERNAMENOTFOUND = "Unregistered username"
ERROR_UNKNOWNCOMMAND = "Unknown command"
ERROR_ADMINPAGE_NOSPEAKER = "No speaker to show"
ERROR_SURVEY_ADDITION_FAILED = 'OPERATION FAILED'
ERROR_FILE_UPDATING = "File writer failed"


OUTPUT_SPEAKER_ADDITION_SUCCEED = "Speaker has been added successfully!"
OUTPUT_SPEAKER_DELETION_SUCCEED = "Speaker has been added successfully!"
OUTPUT_SPEAKER_EDITION_SUCCEED = "Editing Operation Done!"
OUTPUT_ADDING_SURVEY_SUCCEED = "operation succeed. Thanks for your company!"


